name = "VoronoiBinning"
uuid = "0480b74a-4474-4b41-b184-abfd81603c41"
authors = ["Michael Reefe"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
